### ISSUE TITLE
Crear pantalla Nueva RV

### ISSUE THREAD

**Issue by fedesanches** [apollo-utn-frd/apollo-core#17]
La pantalla debe tener la funcionalidad siguiente:

- [x] Asignar puntos en el mapa que se conecten con lineas rectas entre el posterior, actual y siguiente.
- [x] Agregar buscador de Google dentro del mapa.

Por otra parte, al asignar un punto en el mapa se tiene que:

- [x] Se tiene que poder darle un **Titulo** y **descripcion**

**Comment by juanbono** [comment]
completado
