### ISSUE TITLE
Crear pantalla Ver RV

### ISSUE THREAD

**Issue by fedesanches** [apollo-utn-frd/apollo-core#19]
En esta pantalla se muestra la RV que el usuario selecciono. Por un lado debe poder mostrar:
- [x] Mapa real con movimiento que tenga cargados los puntos 
- [x] Al costado se debe mostrar el titulo de cada punto junto con su descripción

Por otra parte se debajo se tiene que mostrar una barra en la que se pueda:
- [x] Marcar como favorita
- [x] Compartir la rv
- [x] Comentar la rv --> esto lleva al usuario directamente a la parte de abajo para agregar el comentario

Mas abajo deben estar los comentarios que posee la rv con la opción para agregar un comentario

**Comment by juanbono** [comment]
Completado
